### ISSUE TITLE
Unnecessary Err

### ISSUE THREAD

**Issue by ArnavK-09** [imranbarbhuiya/pagination.djs#313]
### Issue description

```bash
discord:error - TypeError: Cannot read properties of undefined (reading 'name')
    at new Pagination (/workspaces/rbj/robo-store/node_modules/pagination.djs/src/lib/pagination/Pagination.ts:77:49)
    at Module.default (file:///workspaces/rbj/robo-store/.robo/build/commands/store/products.js:10:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async options (/workspaces/rbj/testing/node_modules/robo.js/src/core/handlers.ts:427:1)
    at async collection (/workspaces/rbj/testing/node_modules/robo.js/src/core/robo.ts:217:1)

```

Error from here 

https://github.com/imranbarbhuiya/pagination.djs/blob/2f66fe07fdbbad0e33207843dca36179ec353ac2/src/lib/pagination/Pagination.ts#L74-L80

### Code sample

```TypeScript
interaction: ChatInputCommandInteraction
```

```ts
const pagination = new Pagination(interaction);
    pagination.setEmbeds(allProducts.map(x => genProductEmbed(x as ProductType)));
    const payloads = pagination.ready();
    const message = await interaction.reply(payloads);
    pagination.paginate(message);
```

### Package version

latest

### Node.js version

20

**Comment by imranbarbhuiya** [comment]
also the issue related to accessing `.construction.name` should be fixed in https://github.com/imranbarbhuiya/pagination.djs/commit/e921bf28a5ef0738147bfadf7b0109db02c5c0d9
